from prompts.templates import (
    JD_EXTRACTION_SYSTEM,
    JD_EXTRACTION_USER,
    MATCH_ANALYSIS_SYSTEM,
    MATCH_ANALYSIS_USER,
    RESUME_PARSE_SYSTEM,
    RESUME_PARSE_USER,
    VISION_RESUME_SYSTEM,
    VISION_RESUME_USER,
)

__all__ = [
    "RESUME_PARSE_SYSTEM",
    "RESUME_PARSE_USER",
    "JD_EXTRACTION_SYSTEM",
    "JD_EXTRACTION_USER",
    "MATCH_ANALYSIS_SYSTEM",
    "MATCH_ANALYSIS_USER",
    "VISION_RESUME_SYSTEM",
    "VISION_RESUME_USER",
]
